package me.tangobee.weathernaut.constants

data class WeatherConstants(
    val code: Int,
    val description: String
)

object WeatherCodes {
    val weatherConstants = listOf(
        WeatherConstants(0, "Clear"),
        WeatherConstants(1, "Clear/Partly Cloudy"),
        WeatherConstants(2, "Partly Cloudy"),
        WeatherConstants(3, "Overcast"),
        WeatherConstants(45, "Fog"),
        WeatherConstants(48, "Rime Fog"),
        WeatherConstants(51, "Light Drizzle"),
        WeatherConstants(53, "Moderate Drizzle"),
        WeatherConstants(55, "Heavy Drizzle"),
        WeatherConstants(56, "Light Freezing Drizzle"),
        WeatherConstants(57, "Heavy Freezing Drizzle"),
        WeatherConstants(61, "Light Rain"),
        WeatherConstants(63, "Moderate Rain"),
        WeatherConstants(65, "Heavy Rain"),
        WeatherConstants(66, "Light Freezing Rain"),
        WeatherConstants(67, "Heavy Freezing Rain"),
        WeatherConstants(71, "Light Snow"),
        WeatherConstants(73, "Moderate Snow"),
        WeatherConstants(75, "Heavy Snow"),
        WeatherConstants(77, "Snow Grains"),
        WeatherConstants(80, "Light Rain Showers"),
        WeatherConstants(81, "Moderate Rain Showers"),
        WeatherConstants(82, "Heavy Rain Showers"),
        WeatherConstants(85, "Light Snow Showers"),
        WeatherConstants(86, "Heavy Snow Showers"),
        WeatherConstants(95, "Slight Thunderstorm"),
        WeatherConstants(96, "Slight Thunderstorm"),
        WeatherConstants(99, "Heavy Thunderstorm")
    )
    val weatherConstants_es = listOf(
        WeatherConstants(0, "Despejado"),
        WeatherConstants(1, "Despejado/Parcialmente Nublado"),
        WeatherConstants(2, "Parcialmente Nublado"),
        WeatherConstants(3, "Nublado"),
        WeatherConstants(45, "Niebla"),
        WeatherConstants(48, "Niebla con Escarcha"),
        WeatherConstants(51, "Llovizna Ligera"),
        WeatherConstants(53, "Llovizna Moderada"),
        WeatherConstants(55, "Llovizna Fuerte"),
        WeatherConstants(56, "Llovizna Ligera Helada"),
        WeatherConstants(57, "Llovizna Fuerte Helada"),
        WeatherConstants(61, "Lluvia Ligera"),
        WeatherConstants(63, "Lluvia Moderada"),
        WeatherConstants(65, "Lluvia Fuerte"),
        WeatherConstants(66, "Lluvia Ligera Helada"),
        WeatherConstants(67, "Lluvia Fuerte Helada"),
        WeatherConstants(71, "Nieve Ligera"),
        WeatherConstants(73, "Nieve Moderada"),
        WeatherConstants(75, "Nieve Fuerte"),
        WeatherConstants(77, "Granos de Nieve"),
        WeatherConstants(80, "Chubascos de Lluvia Ligera"),
        WeatherConstants(81, "Chubascos de Lluvia Moderada"),
        WeatherConstants(82, "Chubascos de Lluvia Fuerte"),
        WeatherConstants(85, "Chubascos de Nieve Ligera"),
        WeatherConstants(86, "Chubascos de Nieve Fuerte"),
        WeatherConstants(95, "Tormenta Ligera"),
        WeatherConstants(96, "Tormenta Ligera"),
        WeatherConstants(99, "Tormenta Fuerte")
    )
    val weatherConstants_fr = listOf(
        WeatherConstants(0, "Clair"),
        WeatherConstants(1, "Dégagé/Partiellement nuageux"),
        WeatherConstants(2, "Partiellement nuageux"),
        WeatherConstants(3, "Couvert"),
        WeatherConstants(45, "Brouillard"),
        WeatherConstants(48, "Brouillard de givre"),
        WeatherConstants(51, "Légère bruine"),
        WeatherConstants(53, "Bruine modérée"),
        WeatherConstants(55, "Grosse bruine"),
        WeatherConstants(56, "Légère bruine verglaçante"),
        WeatherConstants(57, "Forte bruine verglaçante"),
        WeatherConstants(61, "Légère pluie"),
        WeatherConstants(63, "Pluie modérée"),
        WeatherConstants(65, "Grosse pluie"),
        WeatherConstants(66, "Légère pluie verglaçante"),
        WeatherConstants(67, "Forte pluie verglaçante"),
        WeatherConstants(71, "Légère neige"),
        WeatherConstants(73, "Neige modérée"),
        WeatherConstants(75, "Grosse neige"),
        WeatherConstants(77, "Grains de neige"),
        WeatherConstants(80, "Averses légères de pluie"),
        WeatherConstants(81, "Averses modérées de pluie"),
        WeatherConstants(82, "Gros averses de pluie"),
        WeatherConstants(85, "Averses légères de neige"),
        WeatherConstants(86, "Fortes chutes de neige"),
        WeatherConstants(95, "Léger orage"),
        WeatherConstants(96, "Léger orage"),
        WeatherConstants(99, "Fort orage")
    )
    val weatherConstants_de = listOf(
        WeatherConstants(0, "Klar"),
        WeatherConstants(1, "Klar/Teilweise Bewölkt"),
        WeatherConstants(2, "Teilweise Bewölkt"),
        WeatherConstants(3, "Bedeckt"),
        WeatherConstants(45, "Nebel"),
        WeatherConstants(48, "Raureifnebel"),
        WeatherConstants(51, "Leichter Nieselregen"),
        WeatherConstants(53, "Mäßiger Nieselregen"),
        WeatherConstants(55, "Starker Nieselregen"),
        WeatherConstants(56, "Leichter Gefrierender Nieselregen"),
        WeatherConstants(57, "Starker Gefrierender Nieselregen"),
        WeatherConstants(61, "Leichter Regen"),
        WeatherConstants(63, "Mäßiger Regen"),
        WeatherConstants(65, "Starker Regen"),
        WeatherConstants(66, "Leichter Gefrierender Regen"),
        WeatherConstants(67, "Starker Gefrierender Regen"),
        WeatherConstants(71, "Leichter Schnee"),
        WeatherConstants(73, "Mäßiger Schnee"),
        WeatherConstants(75, "Starker Schnee"),
        WeatherConstants(77, "Schneegriesel"),
        WeatherConstants(80, "Leichte Regenschauer"),
        WeatherConstants(81, "Mäßige Regenschauer"),
        WeatherConstants(82, "Starke Regenschauer"),
        WeatherConstants(85, "Leichte Schneeschauer"),
        WeatherConstants(86, "Starke Schneeschauer"),
        WeatherConstants(95, "Leichtes Gewitter"),
        WeatherConstants(96, "Leichtes Gewitter"),
        WeatherConstants(99, "Starkes Gewitter")
    )
}
